### ISSUE TITLE
menu position when there is not enough space

### ISSUE THREAD

**Issue by jharil** [based-ghost/react-functional-select#1]
First of all, congratulations on such a beautiful component. I am very attracted to the way you have implemented the search without delay in the DOM.

I have a doubt...
Will the option of automatic or manual positioning of the menu be implemented when there is not enough space?

An idea: react-select

Thank you!

**Comment by based-ghost** [comment]
@jharil I Appreciate the comments and feedback. Regarding the menu positioning, it looks like you are correct with your observation. I will take some time to look into it and perhaps see how react-select is handling such scenarios.

Thanks again!

**Comment by based-ghost** [comment]
Closing - issue regarding menu needing to be resized in scenarios where there is not enough space available to accommodate the default menuMaxHeight size addressed in commit for **v1.0.0-beta.18**
