### ISSUE TITLE
Order of multi-select tags not preserved.

### ISSUE THREAD

**Issue by dannyvaughton** [based-ghost/react-functional-select#18]
There seems to be an issue with the order of tags when using multi-select.

If I choose `c`, `b`, `a` (in that order) from menuOptions which are by default in this order (`a`, `b`, `c` & `d`), if the data is preserved and the component is re-loaded, the tags are in the order of the menuOptions (`a`, `b`, `c`) and NOT (`c`, `b`, `a`).

The issue arises in this function:

(It's the final reduce function).

https://github.com/based-ghost/react-functional-select/blob/f213fb771a83f6341cf5f809411acae25e6715df/src/utils.ts#L234

I am not confident in changing this function as I'm not sure about the repercussions that I'm unaware of.

**Comment by based-ghost** [comment]
@dannyvaughton - Ya, looks like there were some issues with that specific function when working with multi-select scenarios. The function was trying to do too much validation that really shouldn't be in scope for the package. I published a new version (v2.7.2) that contains a fix - let me know if that solves your use case.

Thanks!

**Comment by dannyvaughton** [comment]
Thanks, dude, yes, that's worked a treat!
