### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by fourteenmeister** [based-ghost/react-functional-select#2]
Error:Error:line (9)TS7016: Could not find a declaration file for module 'react-functional-select'. 
  Try `npm install @types/react-functional-select` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-functional-select';`

**Comment by based-ghost** [comment]
Thanks for reporting this - it looks like I had forgotten to add a `typings` entry in the `package.json` file. This should now be fixed under released version 1.0.9.
