### ISSUE TITLE
How to set selected option from outside?

### ISSUE THREAD

**Issue by ivos** [based-ghost/react-functional-select#22]
Version: 2.9.4

I'm trying to set the selected option / value of the Select from outside of the component. It seems that when I do that, the Select component fires `onOptionChange` with the previous (still current?) value which (probably?) overrides the new value that was just passed in.

Code:

```
import React, { useState } from 'react'
import { Select } from 'react-functional-select'

const initialOptions = [
  { value: 0, label: 'Abc' },
  { value: 1, label: 'Bcd' },
  { value: 2, label: 'Cde' }
]

export default () => {
  const [options, setOptions] = useState(initialOptions)
  const [value, setValue] = useState(null)
  console.log('value', value)

  return <>
    <Select options={options}
            initialValue={value}
            onOptionChange={option => console.log('onOptionChange', option)}
    />
    <button onClick={() => {
      const newOption = { value: 3, label: 'New' }
      setOptions([newOption, ...options])
      setValue(newOption)
    }}>
      Set new value
    </button>
  </>
}
```

Expectations:
- When I click on the "Set new value" button, I expect to have the option with label "New" selected.

Actual behavior:
- The "New" option is not selected.

Console reveals that when I click on the button, the `onOptionChange` callback is fired with the previously selected option (or `null` if none was selected). One might guess that this is an indication that the newly set value is immediately afterwards overridden by the previous value.

Console output:
```
value null
... now click the button...
value {value: 3, label: "New"}
onOptionChange null
```

(All the code examples I found have the selected option assigned solely from the argument passed by the `onOptionChange` callback, including issue #5.)

**Comment by based-ghost** [comment]
Hey @ivos ,

I think what you want to use is the forwarded `ref` property which exposes multiple API methods you can use to manually manipulate the `Select` component value/options - https://based-ghost.github.io/react-functional-select/?path=/story/react-functional-select--methods. In your case, `setValue` is the method that will fulfill your requirements. Here's an updated sample using the code snippet you provided that should outline what you want to accomplish:

```jsx
import React, { useState, useRef } from 'react';
import { Select } from 'react-functional-select';

const initialOptions = [
  { value: 0, label: 'Abc' },
  { value: 1, label: 'Bcd' },
  { value: 2, label: 'Cde' }
];

export default () => {
  const selectRef = useRef(null);
  const [options, setOptions] = useState(initialOptions);

  return (
    <>
      <Select
        ref={selectRef}
	options={options}
        initialValue={null}
      />
      <button onClick={() => {
        const maxValue = options.map(({ value }) => value).sort().pop();
        const value = maxValue + 1;
        const newOption = { value, label: `New Value: ${value}` };

        setOptions([newOption, ...options]);
        selectRef.current.setValue(newOption);
      }}>
        Set new value
      </button>
    </>
  );
};
```

Let me know if you have any other questions - thanks!

**Comment by ivos** [comment]
Thank you, that solves my problem. I haven't looked through the Storybook cases, I was just looking at the Readme on Github which only presents the properties, but not methods, so I wasn't even aware of them - my bad. Thanks again for explanation and a nice source code example, and for this library :)
