### ISSUE TITLE
Mount the dropdown menu outside the parent div

### ISSUE THREAD

**Issue by IsmailM** [based-ghost/react-functional-select#23]
Hi,

I am rendering the select within another component - that requires `overflow: hidden`

This means that I cannot see the dropdown after opening it.

As such, do you think it is possible to add [portaling](https://reactjs.org/docs/portals.html) / Overlay etc. to the dropdown to get around this issue?

I note that [React select](https://react-select.com/advanced#portaling) has a `menuPortalTarget` prop - so something similar would be amazing:

**Comment by based-ghost** [comment]
@IsmailM - Thanks for the reminder for this functionality (I have been meaning to add it). I should have a PR out for this in the next few days.

**Comment by based-ghost** [comment]
@IsmailM - apologies for the the delayed response to this, however, if you still have the need for menu portaling functionality it is now available in the latest version of the package (`react-functional-select@3.0.0`). It is similar to what you would find in `react-select`'s API. For code samples & live demos you check out the new [Portaling Story](https://based-ghost.github.io/react-functional-select/?path=/story/react-functional-select--portaling) I have added to `react-functional-select`'s Storybook.

Thanks again for the suggestion.

**Comment by IsmailM** [comment]
Thank you so much for implementing this. This is very useful.
