### ISSUE TITLE
Custom cursor style on control and/or menu

### ISSUE THREAD

**Issue by carscx** [based-ghost/react-functional-select#9]
Hello, I have reviewed the documentation and the code, but I have not found a way to change the cursor style.

Another possibility is something similar to renderOptionLabel, but for control as well.

Thanks!

**Comment by based-ghost** [comment]
@carscx I think based on what you are trying to accomplish you could utilize the `css` property that exists on the `control` and `menu` nested objects of the `themeConfig` object property - the optional `css` properties are of type `string | FlattenSimpleInterpolation` (pass raw CSS string or if using `styled-components`, CSS interpolated string wrapped in their `css` utility helper). These properties were a late add to the API to account for scenarios like this and provide a little more flexibility. It's a little obscure so its easy to miss. In your case you could pass the following to `themeConfig`:

```
{
  control: {
    css: 'cursor: pointer;'
  },
  menu: {
    css: 'cursor: pointer;'
  }
}
```

Also, check out the second paragraph under 'Theming' on the [Styling Story](https://based-ghost.github.io/react-functional-select/?path=/story/react-functional-select--styling)

**Comment by carscx** [comment]
Thank you,
Previously I had solved it by adding a wrap and using css styles, but it is more elegant to include it in the Theme
